apiVersion: v1
kind: Service
metadata:
  name: generate-1
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: cw-generate
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: generate-2
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: cw-generate
  type: NodePort
# kubectl apply -f app-service.yaml
